---
- name: update web servers
  hosts: webservers
  remote_user: ubuntu

  tasks: 
  - name: Ensure nginx is started
    ansible.builtin.service:
      name: nginx
      state: started
  - name: Ensure nopCommerce430 is started
    ansible.builtin.service:
      name: nopCommerce430
      state: started

